version: 3
silent: true
interval: 500ms
tasks:
  default:
    cmds:
      - task: env
  env:
    cmds:
      - direnv reload
      - nix-direnv-reload
      - updateOlsConfig
  git-gud:
    cmds:
      - git add --all
    silent: true
  run:
    cmds:
      - task: git-gud
      - nix run
  build-glsl:
    sources:
      - ./src/main/**/*.glsl
    cmds:
      - for: sources
        cmd: |
          sokol-shdc -i {{.ITEM}} \
          -o {{replace ".glsl" ".odin" .ITEM}} \
          -l "$(nix eval --raw ".#odinConfig.${system}.extraEnvVars.SLANG")" \
          -f "sokol_odin"
    method: none
  debug:
    deps:
      - build-debug
    cmds:
      - debug-tui
    aliases:
      - d
  debug-dap:
    deps:
      - build-debug
    cmds:
      - debug-dap
  debug-test:
    deps:
      - build-debug-test
    cmds:
      - debugTest-tui
    aliases:
      - d
  debug-test-dap:
    deps:
      - build-debug-test
    cmds:
      - debugTest-dap
  test:
    cmds:
      - task: git-gud
      - runTest
  build-debug:
    cmds:
      - task: git-gud
      - buildDebug
    aliases:
      - bd
  build-debug-test:
    cmds:
      - task: git-gud
      - buildDebugTest
    aliases:
      - bdt
